---
title: "Group Reflection"
editor: visual
---

## Skills inventory

For each skill area, describe what your group actually used it for. If you did not use a skill, say so and note why.

### Functions & refactoring (W2)

*What we did:* We only created a function once (till now), because other repeating tasks were not suitable for functions.

*What worked well:* The one function we created works quite well (its a really simple one)

*What would have been hard:* To create a function that generates our plots. Because our plots use little to no repeating data, a function would have required a large number of arguments as input. It was faster and easier to rewrite the short section that repeated once. The other problem was that we always used different data sets for each chart, which would have required even more arguments for the function. If we had found a dataset that contained all the necessary variables, we could have written a function

### Debugging (W3)

*What we did:* We wrote a significant portion of the code together during calls, where the four of us were able to quickly resolve most errors. Since we had (and still have) widely varying levels of prior knowledge, we were able to help each other effectively within the group. Otherwise, we tried to interpret R's error messages, using AI as a last resort to have the errors explained to us. This allowed us to fix all the errors independently without having to blindly copy code from the AI.

*What worked well:* Helping each other within the group

*What was hard: /*

### Version control & remotes (W4)

*What we did:* We frequently created new branches so that we could all work on different aspects of the project simultaneously. Either a branch was worked on by only one person at a time, or—if multiple people were working on the same branch—we clearly communicated beforehand who was allowed to edit which file to avoid conflicts. Thanks to version control, we could always revert to an earlier state, though we haven't needed to do so (so far). GitHub also ensured that everyone was notified whenever someone else completed a task. About halfway through the project, we adopted a workflow that worked well for everyone: we would call each other at midday to discuss what needed to be done. Afterward, tasks were assigned, and everyone worked on their respective parts, uploading their work once finished. In this way, we worked our way toward completion step by step.

*What worked well:* We started by coding together via a call. Later, we coordinated together, followed by individual coding. Thanks to Git, there were no version conflicts.

*What was hard:* Establishing our system. In the beginning, changes were sometimes made directly to the main branch; due to unclear communication and a failure to create separate branches, people would edit the same file simultaneously, leading to conflicts that could have easily been avoided.

### Quarto websites & collaborative coding (W5)

*What we did:* We experimented with rendering our website and looked at early rendered outputs. This gave us feedback as to what parts of our repository structure worked and what did not.

*What worked well:* Editing the index in \_quarto.yml to give us the desired project structure was luckily very simple and allowed us to fix the structure very quickly.

*What was hard:* During rendering, we did run into conflicts, notably the allbus_mini data set, but we did eventually find the issues and made it work.

### R packages (W6)

*What we did:* After an in-group discussion, we decided not to create a project-specific R package, because our goals did not require the use of complicated and manually generated functions.

*What worked well:* The in-group discussion went very quickly and we came to a fast agreement.

*What was hard:* This week, nothing really.

### Initial data analysis & data cleaning (W7)

*What we did:* After choosing the cumulative allbus data set, we quickly ran into the problem of storage. The original file was over 160MB large and by far exceeded the limit GitHub allowed us to push (100MB). After an in-group discussion, as well as talking to the tutors, we manually filtered the large data set into topics that were relevant to the project and added a reproducible code to track exactly what we cut from the original file. The other files used in this project posed different problems. After the exhausting act of data download was completed, all data sets had to be cleaned next. This too was no easy task, especially creating a helpful time variable was at times complicated to create, because some data sets had strange encodings for the time variable. Other data sets did not follow common structural rules and treated the csv file like a spread sheet with strange subcategories in the middle of the table. Once all data sets were cleaned into a clean and acceptable format, working became much easier.

*What worked well:* Finding Open Source data sets about the topics we wanted to cover.

*What was hard:* Finding **acceptably structured** Open source data sets about the topics we wanted to cover.

### Reproducibility, open data & renv (W9)

*What we did:* Like the individual R package, an in-group discussion lead to the conclusion that Renv was not sensible for the limited scale of our project. What we did have to to in this department is look up the licenses of the data sets we used. Some were easy to find, others were hidden under an enormous amount of layers on several websites. For future projects, we learned that license documentation should be done instantly once one decides to include a data set.

*What worked well:* Coming to unanimous decisions within the group.

*What was hard:* Finding the license for the German unemployment data covered behind a dozen windows on the website of the unemployment agency.

### Analysis & inference strategies (W10)

*What we did:*

*What worked well:*

*What was hard:*

### Communication & visualisation (W11)

*What we did:*

*What worked well:*

*What was hard:*

## Key analytical decisions

### Decision 1: World Bank or allbus?

- In the beginning, we had the option to use either the data from the World Bank, or allbus.

- We decided against the World Bank and for allbus, because we liked that it was one giant data set instead of having to manually construct a data set from the World Bank. This would make documenting the raw data much easier, we thought.

- Note that at this point, we had not run into the problems the allbus data set would impose later down the line.

- In hindsight, choosing the allbus data set probably caused more stress than the World Bank data would have. But at least we learned how to deal with data that is simply too large to be pushed into GitHub.

### Decision 2: allbus 2021 or cumulative allbus?

- After deciding to go with the allbus data, we faced another decision.

- Only analysing one point in time makes it hard to form conclusions about anything.

- We also realized we were completely missing time-variate variables.

- For this reason, we switched to the cumulative allbus data from 1980 to 2023

- After choosing the data, we would run into the problem with the size of the file, but the previous data was no longer an option because we were missing a time variable.

### Decision 3: expand to multiple data sets?

- Realizing that only analyzing opinions without adding objective data would make the analysis between AfD-polling (by then we had agreed on what our dependent variable would be) and multiple factors weak, we decided to add the GDP and the unemployment data to the mix and strengthen our findings

## Workflow & collaboration

*How did we divide work across group members?*

We assigned tasks only as they emerged to be as flexible as possible.

*What branching or Git workflow did we actually use — and did it match the proposal?*

We used the exact strategy as proposed. Every section of tasks was done on its own branch, mostly by only one person at a time. We used a github workflow to ensure strict style according to styler guidelines but intentionally deactivated the compile check due to R just not being made to be used with github workflows.

*What would we change about how we coordinated? /*

## LLM usage

### Usage 1: License checkup

- Google Gemini
- Own suggestions what licenses were correct
- Telling us what licenses belonged to the data set we used. Of course, we still had to look them up, but we could still check afterwards if what we found matched the results from the A.I.

### Usage 2: allbus issue consultation

- Google Gemini
- Solution suggestions
- Besides the group and the tutors, we also consulted with the A.I. about how to work around the problem with the large allbus data set.

### Usage 3: Git issues / conflict resolution

- Google Gemini

- Helpful git commands

- When running into conflicts when using git pull, or anything with git ever actually, the A.I. was often helpful in resolving the issues.
