---
title: "Individual reflection Paul Petras"
format: pdf
editor: visual
---

## Setup & Workflow organisation

I set up the git repository according to the template and added GitHub workflows for style and compile checking as well as branch protection rules. I introduced the branching strategy and was the contact person for problems and troubleshooting with git and GitHub.

Committing directly to the main branch was prohibited by branch protection rules. Every contribution had to go from a separate branch through a pull request. In the pull request, two workflows would run. One workflow checks if the code is correctly formatted according to styler guidelines. The second workflow was intended to compile all committed code and check for errors. One problem emerged, though. To compile the code, every used package had to be added to the workflow. Adding every new package manually would be too exhausting. In Rust, adding a new package would automatically update the lock file, which could be used in the workflow. But in R, one would have to snapshot the project to update the lock file. This would create unnecessary problems when one forgets to snapshot. Thus, I decided to deactivate this check. After the checks have passed, another team member had to approve the changes before the creator of the PR would merge it onto the main branch and instantly delete the merged branch to prevent reusing a merged branch.

## Technical Expertise

Throughout the whole project, I was responsible for all kinds of technical problems with R, RStudio, git, GitHub, and more. I helped with corrupted data sets (e.g., because of using write_csv() to write dta files), programming problems, directory structure, merge conflicts, git SSH-token setup, some RStudio settings, and markdown-related problems.

## Project work

I contributed to the proposal and group reflection. I contributed to finding and formulating research questions. I contributed to finding the right data sets and their licences. In 01_download.R, I helped with troubleshooting problems with the data sets. Some of the data sets had invalid values or formatting in the first rows that had to be removed or fixed. I contributed to the idea of using a cumulative Allbus data set and shrinking it to a GitHub-friendly size in 02_prepare_allbus_dataset.R. I then contributed to 04_eda.R with plots. I contributed to various analytical decisions. Apart from that, I did some debugging and troubleshooting of some of the code.

## Organizational

I helped with rendering the project, deciding on the webpage structure, and hosting the rendered webpage on my github.io page.
